services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_APP_FRONTEND_URL=${VITE_APP_FRONTEND_URL}
      - VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL}
      - CHOKIDAR_USEPOLLING=true

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./scraper:/app
      - /home/debian/simple-web-scraper:/home/debian/simple-web-scraper
    environment:
      - FLASK_ENV=development
      - VITE_APP_FRONTEND_URL=${VITE_APP_FRONTEND_URL}
      - VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL}

networks:
  app_network:
    driver: bridge
    name: my_custom_network