version: '3.8'

services:
  frontend:    
    build: 
      context: frontend/
      dockerfile: Dockerfile
    networks:
      - app_network
    ports: 
      - "49102:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "49103:5000"
    volumes:
      - ./scraper:/app
    environment:
      - FLASK_ENV=development

networks:
  app_network:
    external: true
    name: my_custom_network